baseurl = "/"
title = "Rafael La Buonora"
copyright = "Copyright &copy; 2019 - Rafael La Buonora"
canonifyurls = true
theme = "hugo-kiera"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Rafael La Buonora"
    github = "rlabuonora"
    twitter = "rlabuonora"

[params]
    tagline = "Mi blog de data science"
    favicon = "favicon.png"
