baseurl = "https://rlabuonora.com/"
title = "rlabuonora.com"
copyright = "Copyright &copy; 2019 - Rafael La Buonora"
canonifyurls = true
theme = "hugo-kiera"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

paginate = 16

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Rafael La Buonora"
    github = "rlabuonora"
    twitter = "rlabuonora"

[params]
    tagline = ""
    favicon = "/favicon.png"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    customCSS = ["custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
