---
title: Math Academy Review
author: ''
date: '2025-09-29'
slug: []
categories: []
tags: []
images: []
---


# 

Over the summer, I decided to research how to use LLM's for learning. I have been teaching economics, econometrics and data science for more than a decade, but never got any formal education. The first realization was that to use technology effectively, I needed to learn about the science of learning. 

I found a couple of interesting youtube channels (Justin Su and Benjamin Keep). I also came across Math Academy. Justin Skycak has an in depth review of the scientific literature on learning that caught my eye. It laid out the scientific literature around learning, and how Math Academy leverages it's main findings to optimize learning. While there is no LLM's in MA, it was very much what I was looking for, so I dove right in.

# The Math Academy Way

Ok, so the first thing I like about MA is that is designed to optimize learning,
based on what we know about how the brain works. Other technologies like schools, books, youtube videos and online courses are not. 

As a long time teacher and casual reading of the scientific literature on learning, a lot of the science resonates with me and what I naturally do in the classroom. Some of the principles are very hard to put into practice in a classroom setting, so we naturally pretend the do not exist. Others were quite new to me, so that was useful too!  

## Recognizing information vs. learning.

In my early twenties, I discovered I loved learning. I started listening to podcasts and lectures on youtube daily, mostly about literature, history and economics. That way I learned a lot and discovered great teachers that inspired me to become a teacher myself. The best teachers were the ones that kept you engaged and were able to hold your attention for an hour, so that was what I tried to do in the classroom. 

I didn't realize that I was falling into the trap of passive learning. In this mode, I enjoyed listening to lectures a great deal, got inspired by teachers who could talk for hourse about their area of expertise and even acquired some useful general knowledge. However, it is almost impossible to develop real skills this way. 

As I got older, I became more interested in math and science, and also started worrying about learning something that would make some money. That is about the time where Coursera came out. I learned how to program with a few project based courses from Coursera that revolutionized the way I thought about learning. This made me realize that in order to learn how to do something, you need to spend as much time as possible practicing that skill.  

# Me and math

I was always ok at math. I studied very little in high school, but managed to escape it learning a few derivative formulas and the formula for the roots of a quaratic polynomial. As I advanced in my university courses, I got more interested and managed to get through Calculus, Linear Algebra, Probability and Statistics. I even took a few classed that required Differential Equations and Control Theory. After getting my degree, I taught Econometrics for a few years, so I was pretty good at statistics. 

However, I always knew the building of my math knowledge had very shaky foundations. I had never seen complex numbers, trigonometry and geometry in a course, so had zero knowledge on those topics. Throughout the years, I have always had a growing interest in math, and realize how it underpins all the things I want to learn more about. I pushed a bit to fill in those gaps, and even expand my knowledge a bit further.


So how do you use technology to optimize learning? What are the main findings in the literature that can be leveraged to learn better?

## Cognitive load

Cognitive load is ... . Think of math a a huge puzzle. When you open a math book, you have thousands of puzzle pieces in front of you. If you know what the final picture looks like, it is probably easy to look at each piece and place it in the right place. This is why math teachers are sometimes not that good at teaching. Gauss talked about removing the scaffolds of the proofs.

What Math Academy does is help you manage the cognitive load of putting the puzzle in place. Instead of presenting you with thousands of scattered pieces, it presents parts of the puzzle that are missing just one piece. That way, working through MA feels like adding the last piece of the puzzle all the time. So you get short feedback looks where you can be succesfull and make progress no matter what your current knowledge of the big picture is.

By scaffolding the problems this way, you never get stuck or overwhelmed, and most of your time is spent reinforcing the patterns in your brain that allow you to solve math problems.

Another killer feature of MA is that it has a detailed knowledge graph that records exactly where you are. If you put 20 minutes in you are guaranteed to move towards your goal. Scaffolding and the puzzle metaphor explains this. MA lessons are bite sized, so you know what you are getting into and is quite easy to get a quick win in less than 20 minutes. I can now open a Calculus textbook and knock out a problem or two in 20 minutes because I know the subject, but I cannot do that with a book about a topic I know less of.

This is not to say that studying at MA is easy. Learning math is hard, that is why it is so much fun.

# Retrieval practive

Learning consists of 2 parts: encoding and retrieving. Encoding is when you take information in. You pay attention and try to take in as much as you can. After that, you need to retrieve the information from your brain. This is quite simple, but it is surprising how much you can get out of keeping this simple model in mind. Both parts of learning are crucial, and you can't have one without the other. So, if you don't test what you learn, your brain will forget it. In fact, you need to spend a lot more time testing yourself retrieving what you have learned than consuming information.

You are pulling information out of your brain. That is where the learning happens. If you ever go to the gym, an instructor shows you how to lift a weight. That is necessary for you to get in shape. But if you do not lift the weight yourself, you get zero results. 

A few years ago I wanted to learn Linear Algebra, and found Gilbert Strang's course on youtube. 36 videos of 45 minutes, I could do one or two a day and get through it in a month. Right? Wrong! I knew I needed to spend more time doing practice problems than watching lectures, so I bought the book. I did a lot of problems, but still lacked the structure. 


# Mastery Learning

Mastery learning means you do not progress to more advanced topics until you get very good at the prerequisites. This is one of the principles of Math Academy. You don't get to choose which topic to learn. You enroll in a course and the system makes sure to move you along the path by serving lessons, reviews and quizzes This are basically problems you need to solve to acquire XP points. Lessons and reviews are pretty much the same, but quizzes are timed. This is quite fun, and it also highlights that simply knowing how to do a problem is not enough. You need to be fluent and solve them with a certain degree of automaticity. 

The system is very well calibrated to get a good sense of how well you know the material. That is one of the strenghts of MA. An interesting pattern I fell into was bombing on a quiz, getting served a few review problems, try the quiz again and ace it. According to my reading of the literature, spending an hour on this is the best use of your time when learning math. Of course you could spend that hour in the sacred halls of MIT via youtube and feel like Will Hunting but your brain would discard that information pretty fast.

# Why is Math Academy so good.

- It feels underdeveloped, I hope they don't add too much stuff. 
- It build a very detailed model of you current knowledge, and points

Spending money is good. Having a roadmap and a precise measure of where you stand and where you are going is a powerful way of building a habits. Also, the XP system works. It doesn't have to be fancy, just a short feedback loop that sends my brain the signal that I moved forward. 

- Testing effect are awesome.

Crucial insights from MA: Redundance for inflow of information is inefficient. I still think the best way to get the first exposure Redundance for outflow is not so bad.

I learned a ton with Math Academy. Both math and learning science. Here are a few future avenues I'd like to explore:

I figure I have about a year of material on Math Academy. They are working on more content, so it is likely that it will take longer. I wish they added courses on Game Theory and Information Theory and Physics. I wonder if I can now learn better from traditional materials. Also, can LLM's help re purposing traditional materials?
 




